/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inmobiliaria;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Login extends javax.swing.JFrame {

    static Conexion SQL;
    static Connection conn;
    Statement st = null;
    ResultSet rs = null;

    /*
     * Creates new form Login
     */
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JFrame();
        addInn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        consultTable = new javax.swing.JTable();
        solConsult = new javax.swing.JButton();
        numDocConsult = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        inmuConsult = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        consultInm = new javax.swing.JButton();
        acciones = new javax.swing.JComboBox<>();
        ok = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        newInn = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        areatxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        antigtxt = new javax.swing.JTextField();
        prlabel = new javax.swing.JLabel();
        preciotxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tipoInn = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        patio = new javax.swing.JComboBox<>();
        piscina = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrip = new javax.swing.JTextArea();
        descrtxt = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        arri_vent = new javax.swing.JComboBox<>();
        amobl = new javax.swing.JComboBox<>();
        catalogo = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        inmList = new javax.swing.JTable();
        numDoc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_solicitud = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ar_panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tDoc = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        timetxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        enviarSoli = new javax.swing.JButton();
        regis = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        usertxt = new javax.swing.JTextField();
        passwdtxt = new javax.swing.JPasswordField();
        logIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        home.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        home.setLocationByPlatform(true);
        home.setMinimumSize(new java.awt.Dimension(844, 468));
        home.setResizable(false);

        addInn.setText("Agregar inmueble");
        addInn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addInnActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 172, 193));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        consultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(consultTable);

        solConsult.setText("Consultar Solicitudes");
        solConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solConsultActionPerformed(evt);
            }
        });

        numDocConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numDocConsultActionPerformed(evt);
            }
        });

        jLabel18.setText("Numero de doc:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Solicitudes del inmueble");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Solicitudes del cliente");

        jLabel21.setText("ID del inmueble:");

        jButton2.setText("Consultar Solicitudes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        consultar.setText("Consultar solicitudes");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        consultInm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        consultInm.setText("Consultar inmuebles");
        consultInm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultInmActionPerformed(evt);
            }
        });

        acciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aprobar", "Cerrar" }));

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Acciones");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home.getContentPane());
        home.getContentPane().setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel19))
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel20))
                            .addGroup(homeLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(homeLayout.createSequentialGroup()
                                        .addComponent(numDocConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(solConsult))
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel21)
                                    .addGroup(homeLayout.createSequentialGroup()
                                        .addComponent(acciones, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ok))
                                    .addGroup(homeLayout.createSequentialGroup()
                                        .addComponent(inmuConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2)
                                            .addGroup(homeLayout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel22))))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(consultInm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addInn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(consultInm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addInn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addGap(2, 2, 2)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(solConsult)
                            .addComponent(numDocConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addGap(1, 1, 1)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inmuConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acciones, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        newInn.setLocationByPlatform(true);
        newInn.setMinimumSize(new java.awt.Dimension(654, 515));
        newInn.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(0, 172, 193));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        areatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areatxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Area:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Antiguedad: ");

        prlabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        prlabel.setText("Precio: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tipo de inmueble:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("¿El inmueble está amoblado?");

        tipoInn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "Aparta-Estudio" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Tipo de inmueble:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("¿Tiene patio?");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("¿Tiene piscina?");

        patio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        piscina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piscina, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patio, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(piscina, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        descrip.setColumns(20);
        descrip.setRows(5);
        jScrollPane1.setViewportView(descrip);

        descrtxt.setText("Descripcion adicional:");

        add.setBackground(new java.awt.Color(0, 172, 193));
        add.setText("Agregar");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        arri_vent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arriendo", "Venta" }));

        amobl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        javax.swing.GroupLayout newInnLayout = new javax.swing.GroupLayout(newInn.getContentPane());
        newInn.getContentPane().setLayout(newInnLayout);
        newInnLayout.setHorizontalGroup(
            newInnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(newInnLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(newInnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newInnLayout.createSequentialGroup()
                        .addGroup(newInnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addGroup(newInnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tipoInn, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                                .addComponent(antigtxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(areatxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(prlabel)
                            .addComponent(jLabel7)
                            .addComponent(preciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arri_vent, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amobl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(newInnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descrtxt)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addGroup(newInnLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        newInnLayout.setVerticalGroup(
            newInnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newInnLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newInnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newInnLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoInn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(areatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newInnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newInnLayout.createSequentialGroup()
                        .addComponent(descrtxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(newInnLayout.createSequentialGroup()
                        .addComponent(antigtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(arri_vent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preciotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amobl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        catalogo.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        catalogo.setLocationByPlatform(true);
        catalogo.setMinimumSize(new java.awt.Dimension(996, 575));

        inmList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Area", "Antiguedad", "Arriendo/venta", "precio", "Amoblado", "Patio", "Piscina", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(inmList);

        jLabel11.setText("Numero de documento:");

        t_solicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta", "Arriendo" }));
        t_solicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t_solicitudMouseClicked(evt);
            }
        });
        t_solicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_solicitudActionPerformed(evt);
            }
        });

        jLabel12.setText("Venta/Arriendo");

        jLabel13.setText("Tipo de documento");

        tDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CC", "TI", "CE", "PAS", "NIT" }));

        jLabel14.setText("Nombre completo:");

        timetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetxtActionPerformed(evt);
            }
        });

        jLabel15.setText("Tiempo(en meses) a arrendar:");

        javax.swing.GroupLayout ar_panelLayout = new javax.swing.GroupLayout(ar_panel);
        ar_panel.setLayout(ar_panelLayout);
        ar_panelLayout.setHorizontalGroup(
            ar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ar_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tDoc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(39, 39, 39)
                .addGroup(ar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(timetxt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)))
        );
        ar_panelLayout.setVerticalGroup(
            ar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ar_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ar_panelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ar_panelLayout.createSequentialGroup()
                        .addGroup(ar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(ar_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tDoc)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );

        jLabel17.setText("Para hacer la solicitud seleccione un inmueble de la lista");

        enviarSoli.setText("Enviar solicitud");
        enviarSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarSoliActionPerformed(evt);
            }
        });

        regis.setText("Registrar");
        regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout catalogoLayout = new javax.swing.GroupLayout(catalogo.getContentPane());
        catalogo.getContentPane().setLayout(catalogoLayout);
        catalogoLayout.setHorizontalGroup(
            catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catalogoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(catalogoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(enviarSoli)
                        .addGap(50, 50, 50))
                    .addGroup(catalogoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(catalogoLayout.createSequentialGroup()
                        .addGroup(catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(catalogoLayout.createSequentialGroup()
                                .addGroup(catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(t_solicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ar_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(regis)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        catalogoLayout.setVerticalGroup(
            catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catalogoLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, catalogoLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(catalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numDoc)
                            .addComponent(t_solicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ar_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviarSoli, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setName("login"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 172, 193));

        usertxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usertxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usertxt.setPreferredSize(new java.awt.Dimension(7, 20));
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });

        passwdtxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        logIn.setText("Iniciar Sesión");
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/lock.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usertxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(logIn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwdtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logIn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        jButton1.setText("Ver catalogo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed

        if (usertxt.getText().equalsIgnoreCase("admin") && passwdtxt.getText().equalsIgnoreCase("admin")) {
            home.setVisible(true);
            acciones.setVisible(false);
            ok.setVisible(false);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Contraseña o usuario incorrecto",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_logInActionPerformed

    private void areatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areatxtActionPerformed

    private void addInnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addInnActionPerformed
        newInn.setVisible(true);
    }//GEN-LAST:event_addInnActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        String tipoIn = "'" + tipoInn.getSelectedItem() + "'";
        String areaa = "'" + areatxt.getText() + "'";
        String antigue = "'" + antigtxt.getText() + "'";
        String aV = "'" + arri_vent.getSelectedItem() + "'";
        String precioo = "'" + preciotxt.getText() + "'";
        String amob = "'" + amobl.getSelectedItem() + "'";
        String patioo = "'" + patio.getSelectedItem() + "'";
        String piscinaa = "'" + piscina.getSelectedItem() + "'";
        String descr = "''";

        if (descrip.getText().isEmpty()) {
            descr = "''";
        } else {
            descr = "'" + descrip.getText() + "'";
        }

        try {
            if (allGood()) {
                st = conn.createStatement();
                st.executeUpdate("INSERT INTO inmueble values(" + generarIdInmueble() + ", " + tipoIn + ", " + areaa + ", " + antigue + ", " + aV + ", " + precioo + ", " + amob + ", " + patioo + ", " + piscinaa + ", " + descr + ", " + "null" + ")");
                JOptionPane.showMessageDialog(this,
                        "El inmueble ha sido agregado correctamente");
                cleantxt();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Ingrese todos los campos",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addActionPerformed

    private boolean allGood() {
        if (areatxt.getText().isEmpty() || antigtxt.getText().isEmpty() || preciotxt.getText().isEmpty()) {
            return false;
        }

        return true;
    }

    private void cleantxt() {
        areatxt.setText("");
        antigtxt.setText("");
        preciotxt.setText("");
        descrip.setText("");
    }

    private String getIdInm() {
        String value = "";
        try {
            int column = 0;
            int row = inmList.getSelectedRow();
            value = inmList.getModel().getValueAt(row, column).toString();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "No has seleccionado un inmueble",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            value = "";
        }
        return value;
    }

    private String getIdGeneral(int columna) {
        String value = "";
        try {
            int column = columna;
            int row = consultTable.getSelectedRow();
            value = consultTable.getModel().getValueAt(row, column).toString();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "No has seleccionado un inmueble",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            value = "";
        }
        return value;
    }

    private boolean isRegistered(String doc) {
        boolean val = true;
        try {
            st = conn.createStatement();
            rs = st.executeQuery("select * from cliente where numDoc = " + doc);
            val = rs.next(); //next() returns false if there are no-rows retrieved 
            if (val == false) {
                return val;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return val;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        catalogo.setVisible(true);
        this.dispose();
        ar_panel.setVisible(false);
        regis.setVisible(false);
        DefaultTableModel model = (DefaultTableModel) inmList.getModel();

        try {
            st = conn.createStatement();
            rs = st.executeQuery("select * from inmueble where idcl is null");

            if (rs.next()) {

                do {
                    Object[] row = {rs.getString("idinmueble"), rs.getString("tipo"), rs.getString("area"), rs.getString("antiguedad"), rs.getString("arri_vent"), rs.getString("precio"), rs.getString("amoblado"), rs.getString("patio"), rs.getString("piscina"), rs.getString("descripcion")};
                    model.addRow(row);
                } while (rs.next());

            } else {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron inmuebles registrados",
                        "Información",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        //inmList = new JTable(data, columnNames);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void timetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timetxtActionPerformed

    private void t_solicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_solicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_solicitudActionPerformed

    private void t_solicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t_solicitudMouseClicked


    }//GEN-LAST:event_t_solicitudMouseClicked

    public static int generarId() { //crea id aleatorio para las solicitudes
        return (int) (100000 * Math.random());
    }

    public static int generarIdUser() { //crea id aleatorio para los usuarios
        return (int) (1000 * Math.random());
    }

    public static int generarIdInmueble() { //crea id aleatorio para los inmuebles
        return (int) (10000 * Math.random());
    }


    private void enviarSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarSoliActionPerformed

        if (isRegistered(numDoc.getText())) {
            if (!"".equals(getIdInm())) {
                try {
                    ar_panel.setVisible(false);
                    regis.setVisible(false);
                    st = conn.createStatement();
                    st.executeUpdate("INSERT INTO solicitud values (" + generarId() + ",  (select idcliente from cliente where numDoc = '" + numDoc.getText() + "'), " + getIdInm() + ", " + "'Pendiente'" + ", '" + timetxt.getText() + "', '" + t_solicitud.getSelectedItem() + "')");
                    JOptionPane.showMessageDialog(this,
                            "Solicitud enviada con exito",
                            "Información",
                            JOptionPane.WARNING_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Parece que no estas registrado, te pediremos unos datos para hacer tu registro.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            ar_panel.setVisible(true);
            regis.setVisible(true);
        }

    }//GEN-LAST:event_enviarSoliActionPerformed

    private void regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisActionPerformed

        try {
            int idUser = generarIdUser();
            st = conn.createStatement();
            st.executeUpdate("INSERT INTO cliente values(" + idUser + ", '" + tDoc.getSelectedItem().toString() + "', '" + numDoc.getText() + "', '" + nametxt.getText() + "')");

            JOptionPane.showMessageDialog(this,
                    "Usuario Registrado",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);

            ar_panel.setVisible(false);
            regis.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_regisActionPerformed

    private void numDocConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numDocConsultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numDocConsultActionPerformed

    private void solConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solConsultActionPerformed
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Inmueble", "Nombre", "Estado", "Tiempo", "Tipo"}, 0);
        try {
            st = conn.createStatement();
            rs = st.executeQuery("select idSolicitud, idinmueble,nombre, estado, tiempo, tipo_tran from solicitud, cliente where solicitud.idcliente = (select idcliente from cliente where numDoc = '" + numDocConsult.getText() + "' ) and solicitud.idcliente = cliente.idcliente");
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron solicitudes",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
            } else {

                System.out.println(rs.getString("idSolicitud") + " " + rs.getString("idinmueble") + " " + rs.getString("nombre") + " " + rs.getString("estado") + " " + rs.getString("tiempo") + " " + rs.getString("tipo_tran"));
                do {
                    model.addRow(new Object[]{rs.getString("idSolicitud"), rs.getString("idinmueble"), rs.getString("nombre"), rs.getString("estado"), rs.getString("tiempo"), rs.getString("tipo_tran")});
                } while (rs.next());

                consultTable.setModel(model);
                numDocConsult.setText("");

            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_solConsultActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) consultTable.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        model.addColumn("ID");
        model.addColumn("N° de solicitudes");
        try {
            st = conn.createStatement();
            rs = st.executeQuery("SELECT COUNT(*) as cuenta FROM solicitud where idinmueble = " + inmuConsult.getText());
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron solicitudes",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
            } else {

                Object[] row = {inmuConsult.getText(), rs.getString("cuenta")};
                inmuConsult.setText("");
                model.addRow(row);

            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed

        DefaultTableModel model = new DefaultTableModel(new String[]{"ID", "Inmueble", "Nombre", "Estado", "Tiempo", "Tipo"}, 0);
        ok.setVisible(true);
        acciones.setVisible(true);
        try {
            st = conn.createStatement();
            rs = st.executeQuery("select idSolicitud, idinmueble,nombre, estado, tiempo, tipo_tran from solicitud, cliente where solicitud.idcliente = cliente.idcliente");
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this,
                        "No se encontraron solicitudes",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
            } else {

                do {
                    model.addRow(new Object[]{rs.getString("idSolicitud"), rs.getString("idinmueble"), rs.getString("nombre"), rs.getString("estado"), rs.getString("tiempo"), rs.getString("tipo_tran")});
                } while (rs.next());
                consultTable.setModel(model);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultarActionPerformed

    private void actualizarSolicitud(java.awt.event.ActionEvent evt, String estado) {
        try {
            st = conn.createStatement();
            st.executeUpdate("UPDATE solicitud SET estado = '" + estado + "' where idSolicitud = " + getIdGeneral(0));
            consultarActionPerformed(evt);
            JOptionPane.showMessageDialog(this,
                    "Estado Actualizado",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setCerrada() {
        try {
            st = conn.createStatement();
            st.executeUpdate("UPDATE inmueble SET idcl = null where idinmueble = " + getIdGeneral(1));

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setDueño() {
        try {
            st = conn.createStatement();
            st.executeUpdate("UPDATE inmueble SET idcl = (select idcliente from solicitud where idSolicitud = " + getIdGeneral(0) + ") where idinmueble = " + getIdGeneral(1));

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if (acciones.getSelectedIndex() == 0) {
            setDueño();
            actualizarSolicitud(evt, "Resuelta");

        } else {

            setCerrada();
            actualizarSolicitud(evt, "Cerrada");
        }
    }//GEN-LAST:event_okActionPerformed

    private void consultInmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultInmActionPerformed
        DefaultTableModel model = new DefaultTableModel(new String[]{"Inmueble", "Tipo", "Arriendo/Venta", "Estado"}, 0);
        try {
            String own = null;
            ok.setVisible(false);
            acciones.setVisible(false);
            st = conn.createStatement();
            rs = st.executeQuery("select idinmueble, tipo,arri_vent, idcl from inmueble");

            while (rs.next()) {
                own = rs.getString("idcl");
                if (own == null) {
                    model.addRow(new Object[]{rs.getString("idinmueble"), rs.getString("tipo"), rs.getString("arri_vent"), "Disponible"});
                } else {
                    model.addRow(new Object[]{rs.getString("idinmueble"), rs.getString("tipo"), rs.getString("arri_vent"), "Vendido/Arrendado"});
                }
            }
            consultTable.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_consultInmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        SQL = new Conexion();
        conn = SQL.getConnection();

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> acciones;
    private javax.swing.JButton add;
    private javax.swing.JButton addInn;
    private javax.swing.JComboBox<String> amobl;
    private javax.swing.JTextField antigtxt;
    private static javax.swing.JPanel ar_panel;
    private javax.swing.JTextField areatxt;
    private javax.swing.JComboBox<String> arri_vent;
    private javax.swing.JFrame catalogo;
    private javax.swing.JButton consultInm;
    private javax.swing.JTable consultTable;
    private javax.swing.JButton consultar;
    private javax.swing.JTextArea descrip;
    private javax.swing.JLabel descrtxt;
    private javax.swing.JButton enviarSoli;
    private javax.swing.JFrame home;
    private javax.swing.JTable inmList;
    private javax.swing.JTextField inmuConsult;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logIn;
    private javax.swing.JTextField nametxt;
    private javax.swing.JFrame newInn;
    private javax.swing.JTextField numDoc;
    private javax.swing.JTextField numDocConsult;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField passwdtxt;
    private javax.swing.JComboBox<String> patio;
    private javax.swing.JComboBox<String> piscina;
    private javax.swing.JTextField preciotxt;
    private javax.swing.JLabel prlabel;
    private javax.swing.JButton regis;
    private javax.swing.JButton solConsult;
    private javax.swing.JComboBox<String> tDoc;
    private javax.swing.JComboBox<String> t_solicitud;
    private javax.swing.JTextField timetxt;
    private javax.swing.JComboBox<String> tipoInn;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
